<?php
/**
 * CustomerPaymentApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * (v1.0) Dynamics 365 Business Central
 *
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerPaymentApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerPaymentApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteCustomerPayment
     *
     * Deletes an object of type customerPayment in Dynamics 365 Business Central.
     *
     */
    public function testDeleteCustomerPayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCustomerPaymentForCustomerPaymentJournal
     *
     * Deletes an object of type customerPayment in Dynamics 365 Business Central.
     *
     */
    public function testDeleteCustomerPaymentForCustomerPaymentJournal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomerPayment
     *
     * Retrieve the properties and relationships of an object of type customerPayment for Dynamics 365 Business Central..
     *
     */
    public function testGetCustomerPayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomerPaymentForCustomerPaymentJournal
     *
     * Retrieve the properties and relationships of an object of type customerPayment for Dynamics 365 Business Central..
     *
     */
    public function testGetCustomerPaymentForCustomerPaymentJournal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCustomerPayments
     *
     * Returns a list of customerPayments.
     *
     */
    public function testListCustomerPayments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCustomerPaymentsForCustomerPaymentJournal
     *
     * Returns a list of customerPayments.
     *
     */
    public function testListCustomerPaymentsForCustomerPaymentJournal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchCustomerPayment
     *
     * Updates an object of type customerPayment in Dynamics 365 Business Central.
     *
     */
    public function testPatchCustomerPayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchCustomerPaymentForCustomerPaymentJournal
     *
     * Updates an object of type customerPayment in Dynamics 365 Business Central.
     *
     */
    public function testPatchCustomerPaymentForCustomerPaymentJournal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postCustomerPayment
     *
     * Creates an object of type customerPayment in Dynamics 365 Business Central.
     *
     */
    public function testPostCustomerPayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postCustomerPaymentForCustomerPaymentJournal
     *
     * Creates an object of type customerPayment in Dynamics 365 Business Central.
     *
     */
    public function testPostCustomerPaymentForCustomerPaymentJournal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
