<?php
/**
 * PdfDocumentApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * (v1.0) Dynamics 365 Business Central
 *
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PdfDocumentApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PdfDocumentApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getPdfDocument
     *
     * Retrieve the properties and relationships of an object of type pdfDocument for Dynamics 365 Business Central..
     *
     */
    public function testGetPdfDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPdfDocumentForPurchaseInvoice
     *
     * Retrieve the properties and relationships of an object of type pdfDocument for Dynamics 365 Business Central..
     *
     */
    public function testGetPdfDocumentForPurchaseInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPdfDocumentForSalesCreditMemo
     *
     * Retrieve the properties and relationships of an object of type pdfDocument for Dynamics 365 Business Central..
     *
     */
    public function testGetPdfDocumentForSalesCreditMemo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPdfDocumentForSalesInvoice
     *
     * Retrieve the properties and relationships of an object of type pdfDocument for Dynamics 365 Business Central..
     *
     */
    public function testGetPdfDocumentForSalesInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPdfDocumentForSalesQuote
     *
     * Retrieve the properties and relationships of an object of type pdfDocument for Dynamics 365 Business Central..
     *
     */
    public function testGetPdfDocumentForSalesQuote()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPdfDocument
     *
     * Returns a list of pdfDocument.
     *
     */
    public function testListPdfDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPdfDocumentForPurchaseInvoice
     *
     * Returns a list of pdfDocument.
     *
     */
    public function testListPdfDocumentForPurchaseInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPdfDocumentForSalesCreditMemo
     *
     * Returns a list of pdfDocument.
     *
     */
    public function testListPdfDocumentForSalesCreditMemo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPdfDocumentForSalesInvoice
     *
     * Returns a list of pdfDocument.
     *
     */
    public function testListPdfDocumentForSalesInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPdfDocumentForSalesQuote
     *
     * Returns a list of pdfDocument.
     *
     */
    public function testListPdfDocumentForSalesQuote()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
