<?php
/**
 * PictureApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * (v1.0) Dynamics 365 Business Central
 *
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PictureApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PictureApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deletePicture
     *
     * Deletes an object of type picture in Dynamics 365 Business Central.
     *
     */
    public function testDeletePicture()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePictureForCustomer
     *
     * Deletes an object of type picture in Dynamics 365 Business Central.
     *
     */
    public function testDeletePictureForCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePictureForEmployee
     *
     * Deletes an object of type picture in Dynamics 365 Business Central.
     *
     */
    public function testDeletePictureForEmployee()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePictureForItem
     *
     * Deletes an object of type picture in Dynamics 365 Business Central.
     *
     */
    public function testDeletePictureForItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePictureForVendor
     *
     * Deletes an object of type picture in Dynamics 365 Business Central.
     *
     */
    public function testDeletePictureForVendor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPicture
     *
     * Retrieve the properties and relationships of an object of type picture for Dynamics 365 Business Central..
     *
     */
    public function testGetPicture()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPictureForCustomer
     *
     * Retrieve the properties and relationships of an object of type picture for Dynamics 365 Business Central..
     *
     */
    public function testGetPictureForCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPictureForEmployee
     *
     * Retrieve the properties and relationships of an object of type picture for Dynamics 365 Business Central..
     *
     */
    public function testGetPictureForEmployee()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPictureForItem
     *
     * Retrieve the properties and relationships of an object of type picture for Dynamics 365 Business Central..
     *
     */
    public function testGetPictureForItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPictureForVendor
     *
     * Retrieve the properties and relationships of an object of type picture for Dynamics 365 Business Central..
     *
     */
    public function testGetPictureForVendor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPicture
     *
     * Returns a list of picture.
     *
     */
    public function testListPicture()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPictureForCustomer
     *
     * Returns a list of picture.
     *
     */
    public function testListPictureForCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPictureForEmployee
     *
     * Returns a list of picture.
     *
     */
    public function testListPictureForEmployee()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPictureForItem
     *
     * Returns a list of picture.
     *
     */
    public function testListPictureForItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPictureForVendor
     *
     * Returns a list of picture.
     *
     */
    public function testListPictureForVendor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchPicture
     *
     * Updates an object of type picture in Dynamics 365 Business Central.
     *
     */
    public function testPatchPicture()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchPictureForCustomer
     *
     * Updates an object of type picture in Dynamics 365 Business Central.
     *
     */
    public function testPatchPictureForCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchPictureForEmployee
     *
     * Updates an object of type picture in Dynamics 365 Business Central.
     *
     */
    public function testPatchPictureForEmployee()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchPictureForItem
     *
     * Updates an object of type picture in Dynamics 365 Business Central.
     *
     */
    public function testPatchPictureForItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchPictureForVendor
     *
     * Updates an object of type picture in Dynamics 365 Business Central.
     *
     */
    public function testPatchPictureForVendor()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
