<?php
/**
 * SalesInvoiceApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * (v1.0) Dynamics 365 Business Central
 *
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SalesInvoiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SalesInvoiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cancelActionSalesInvoices
     *
     * Performs the cancel action for salesInvoices entity.
     *
     */
    public function testCancelActionSalesInvoices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cancelAndSendActionSalesInvoices
     *
     * Performs the cancelAndSend action for salesInvoices entity.
     *
     */
    public function testCancelAndSendActionSalesInvoices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteSalesInvoice
     *
     * Deletes an object of type salesInvoice in Dynamics 365 Business Central.
     *
     */
    public function testDeleteSalesInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSalesInvoice
     *
     * Retrieve the properties and relationships of an object of type salesInvoice for Dynamics 365 Business Central..
     *
     */
    public function testGetSalesInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSalesInvoices
     *
     * Returns a list of salesInvoices.
     *
     */
    public function testListSalesInvoices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for makeCorrectiveCreditMemoActionSalesInvoices
     *
     * Performs the makeCorrectiveCreditMemo action for salesInvoices entity.
     *
     */
    public function testMakeCorrectiveCreditMemoActionSalesInvoices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchSalesInvoice
     *
     * Updates an object of type salesInvoice in Dynamics 365 Business Central.
     *
     */
    public function testPatchSalesInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postActionSalesInvoices
     *
     * Performs the post action for salesInvoices entity.
     *
     */
    public function testPostActionSalesInvoices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postAndSendActionSalesInvoices
     *
     * Performs the postAndSend action for salesInvoices entity.
     *
     */
    public function testPostAndSendActionSalesInvoices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postSalesInvoice
     *
     * Creates an object of type salesInvoice in Dynamics 365 Business Central.
     *
     */
    public function testPostSalesInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendActionSalesInvoices
     *
     * Performs the send action for salesInvoices entity.
     *
     */
    public function testSendActionSalesInvoices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
