<?php
/**
 * SalesOrderApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * (v1.0) Dynamics 365 Business Central
 *
 * (v1.0) Business Central Standard APIs
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SalesOrderApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SalesOrderApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteSalesOrder
     *
     * Deletes an object of type salesOrder in Dynamics 365 Business Central.
     *
     */
    public function testDeleteSalesOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSalesOrder
     *
     * Retrieve the properties and relationships of an object of type salesOrder for Dynamics 365 Business Central..
     *
     */
    public function testGetSalesOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listSalesOrders
     *
     * Returns a list of salesOrders.
     *
     */
    public function testListSalesOrders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchSalesOrder
     *
     * Updates an object of type salesOrder in Dynamics 365 Business Central.
     *
     */
    public function testPatchSalesOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postSalesOrder
     *
     * Creates an object of type salesOrder in Dynamics 365 Business Central.
     *
     */
    public function testPostSalesOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for shipAndInvoiceActionSalesOrders
     *
     * Performs the shipAndInvoice action for salesOrders entity.
     *
     */
    public function testShipAndInvoiceActionSalesOrders()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
